# -*- coding: utf-8 -*-
"""CODE FOR RASPBERRY PI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G9aqxn4GjItPY3VLHPIB6ch6griKyqA7
"""

import cv2
import numpy as np
from picamera2 import Picamera2

# 1. Setup the camera
picam2 = Picamera2()
picam2.configure(picam2.create_preview_configuration(main={"format": "RGB888", "size": (640, 480)}))
picam2.start()

print("Press 'q' to quit...")

try:
    while True:
        # Capture a frame
        frame = picam2.capture_array()

        # Convert to Grayscale for easier processing
        gray = cv2.cvtColor(frame, cv2.COLOR_RGB2GRAY)

        # Detect Edges using Canny
        edges = cv2.Canny(gray, 50, 150, apertureSize=3)

        # Detect Straight Lines using HoughLinesP (Probabilistic)
        lines = cv2.HoughLinesP(edges, 1, np.pi/180, threshold=135, minLineLength=90, maxLineGap=5)

        # Draw the red lines
        if lines is not None:
            for line in lines:
                x1, y1, x2, y2 = line[0]
                # (0, 0, 255) is RED in BGR color space
                cv2.line(frame, (x1, y1), (x2, y2), (255, 0, 0), 3)

        # Show the result
        cv2.imshow('Straight Edge Detection', frame)

        # Break loop on 'q' key
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

finally:
    picam2.stop()
    cv2.destroyAllWindows()